# Generated by Django 4.1.3 on 2022-11-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioProjects',
            new_name='PortfolioProject',
        ),
        migrations.RenameModel(
            old_name='Recommendations',
            new_name='Recommendation',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
