# Generated by Django 4.1.3 on 2022-11-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_portfolioprojects_portfolioproject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeitem',
            name='working_period_from',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='Год начала работы'),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='working_period_to',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='Год окончания работы'),
        ),
    ]
