# Generated by Django 4.1.3 on 2022-11-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_resumeitem_working_period_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="avatar",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="photos/avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="resumeitem",
            name="working_period_from",
            field=models.IntegerField(
                choices=[
                    (2000, 2000),
                    (2001, 2001),
                    (2002, 2002),
                    (2003, 2003),
                    (2004, 2004),
                    (2005, 2005),
                    (2006, 2006),
                    (2007, 2007),
                    (2008, 2008),
                    (2009, 2009),
                    (2010, 2010),
                    (2011, 2011),
                    (2012, 2012),
                    (2013, 2013),
                    (2014, 2014),
                    (2015, 2015),
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                ],
                default=2022,
                verbose_name="Год начала работы",
            ),
        ),
        migrations.AlterField(
            model_name="resumeitem",
            name="working_period_to",
            field=models.IntegerField(
                choices=[
                    (2000, 2000),
                    (2001, 2001),
                    (2002, 2002),
                    (2003, 2003),
                    (2004, 2004),
                    (2005, 2005),
                    (2006, 2006),
                    (2007, 2007),
                    (2008, 2008),
                    (2009, 2009),
                    (2010, 2010),
                    (2011, 2011),
                    (2012, 2012),
                    (2013, 2013),
                    (2014, 2014),
                    (2015, 2015),
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                ],
                default=2022,
                verbose_name="Год окончания работы",
            ),
        ),
    ]
