# Generated by Django 4.1.3 on 2022-11-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_recommendation_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeitem',
            options={'ordering': ['-working_period_to']},
        ),
    ]
