# Generated by Django 4.1.3 on 2022-11-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_resumeitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
    ]
