# Generated by Django 4.1.3 on 2022-11-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_recommendation_address_en_recommendation_address_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='address_af',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ar_dz',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ast',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_be',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_bn',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_bs',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ca',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_cs',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_cy',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_da',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_dsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_el',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_en_au',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_en_gb',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_eo',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_es_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_es_co',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_es_mx',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_es_ni',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_es_ve',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_eu',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_fy',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ga',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_gd',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_gl',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_hi',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_hr',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_hsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_hu',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ia',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ig',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_io',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_is',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ka',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_kab',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_km',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_kn',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ko',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_lb',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_lv',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_mk',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ml',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_mr',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ms',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_my',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_nb',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ne',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_nn',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_os',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_pa',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_pl',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ro',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_sk',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_sl',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_sq',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_sr',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_sr_latn',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ta',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_te',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_tg',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_th',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_tk',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_tt',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_udm',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ur',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_vi',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_zh_hant',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_af',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ar_dz',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ast',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_be',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_bn',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_bs',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ca',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_cs',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_cy',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_da',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_dsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_el',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_en_au',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_en_gb',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_eo',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_es_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_es_co',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_es_mx',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_es_ni',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_es_ve',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_eu',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_fy',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ga',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_gd',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_gl',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_hi',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_hr',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_hsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_hu',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ia',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ig',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_io',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_is',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ka',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_kab',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_km',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_kn',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ko',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_lb',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_lv',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_mk',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ml',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_mr',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ms',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_my',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_nb',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ne',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_nn',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_os',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_pa',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_pl',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ro',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_sk',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_sl',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_sq',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_sr',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_sr_latn',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ta',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_te',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_tg',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_th',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_tk',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_tt',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_udm',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ur',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_zh_hant',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_af',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ar_dz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ast',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_be',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_bn',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_bs',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ca',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_cs',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_cy',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_da',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_dsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_el',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_en_au',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_en_gb',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_eo',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_es_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_es_co',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_es_mx',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_es_ni',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_es_ve',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_eu',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_fy',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ga',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_gd',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_gl',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_hi',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_hr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_hsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_hu',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ia',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ig',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_io',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_is',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ka',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_kab',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_km',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_kn',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ko',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_lb',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_lv',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_mk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ml',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_mr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ms',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_my',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_nb',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ne',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_nn',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_os',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_pa',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_pl',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ro',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_sk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_sl',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_sq',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_sr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_sr_latn',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ta',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_te',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_tg',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_th',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_tk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_tt',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_udm',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ur',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_vi',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_af',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ar_dz',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ast',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_be',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_bn',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_bs',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ca',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_cs',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_cy',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_da',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_dsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_el',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_en_au',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_en_gb',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_eo',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_es_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_es_co',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_es_mx',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_es_ni',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_es_ve',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_eu',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_fy',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ga',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_gd',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_gl',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_hi',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_hr',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_hsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_hu',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ia',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ig',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_io',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_is',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ka',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_kab',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_km',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_kn',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ko',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_lb',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_lv',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_mk',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ml',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_mr',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ms',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_my',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_nb',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ne',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_nn',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_os',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_pa',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_pl',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ro',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_sk',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_sl',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_sq',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_sr',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_sr_latn',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ta',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_te',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_tg',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_th',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_tk',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_tt',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_udm',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ur',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_vi',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_zh_hant',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
    ]
