# Generated by Django 4.1.3 on 2022-11-15 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_recommendation_address_af_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='address_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='resume_category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.resumecategory', verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='resume_category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.resumecategory', verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='resume_category_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.resumecategory', verbose_name='Заголовок в резюме'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='working_place_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Место работы'),
        ),
    ]
