# Generated by Django 4.1.3 on 2022-11-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_recommendation_address_en_recommendation_address_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='address_uz',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='resumecategory',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='resumecategory',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='resumecategory',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='resume_category_en',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='resume_category_ru',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='resume_category_uz',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='working_place_en',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='working_place_ru',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='working_place_uz',
        ),
    ]
